/**
 * A finished take for `SAMPLE_MARKDOWN`, so the stage can be seen without an
 * API key.
 *
 * It is stored in exactly the shape the director model returns and goes through
 * the same `validatePlan` path as a live response — so it is also the reference
 * example of what good output looks like, including the table and code rules.
 */
export const DEMO_RESPONSE = {
  title: 'Why your battery dies in winter',
  segments: [
    {
      text: 'Your phone hits thirty percent in the cold and just dies.',
      sourceKind: 'prose',
      blockIndex: 0,
      voice: 'af_heart',
      speed: 1.12,
      pitchCents: 80,
      gain: 1.15,
      pauseAfterMs: 200,
      emphasis: ['dies'],
      visual: {
        type: 'stat',
        value: '30%',
        label: 'still in the tank when a cold phone gives up',
      },
    },
    {
      text: "Here's the thing. That energy is still in there.",
      sourceKind: 'prose',
      blockIndex: 1,
      voice: 'af_heart',
      speed: 1.05,
      pitchCents: 30,
      gain: 1.0,
      pauseAfterMs: 340,
      emphasis: ['still'],
      visual: null,
    },
    {
      text: "It just can't get out.",
      sourceKind: 'prose',
      blockIndex: 1,
      voice: 'af_kore',
      speed: 0.86,
      pitchCents: -160,
      gain: 1.2,
      pauseAfterMs: 620,
      emphasis: ['out'],
      visual: {
        type: 'quote',
        text: "Lithium cells don't lose charge in the cold. They lose access to it.",
      },
    },
    {
      text: 'Inside every cell, lithium ions shuttle between two electrodes through a liquid.',
      sourceKind: 'prose',
      blockIndex: 2,
      voice: 'af_heart',
      speed: 1.06,
      pitchCents: 20,
      gain: 1.0,
      pauseAfterMs: 140,
      emphasis: ['shuttle'],
      visual: null,
    },
    {
      text: 'Cold thickens that liquid.',
      sourceKind: 'prose',
      blockIndex: 2,
      voice: 'af_heart',
      speed: 0.92,
      pitchCents: -60,
      gain: 1.1,
      pauseAfterMs: 280,
      emphasis: ['thickens'],
      visual: {
        type: 'flow',
        title: 'what the cold actually does',
        steps: ['Electrolyte thickens', 'Ions slow down', 'Resistance climbs', 'Voltage sags'],
      },
    },
    {
      text: 'The ions crawl, internal resistance climbs, and the voltage sags the moment you ask for anything.',
      sourceKind: 'prose',
      blockIndex: 2,
      voice: 'af_heart',
      speed: 1.14,
      pitchCents: 50,
      gain: 1.0,
      pauseAfterMs: 220,
      emphasis: ['sags'],
      visual: null,
    },
    {
      text: 'Your phone reads that sagging voltage and calls it empty.',
      sourceKind: 'prose',
      blockIndex: 2,
      voice: 'am_puck',
      speed: 1.0,
      pitchCents: -90,
      gain: 1.12,
      pauseAfterMs: 520,
      emphasis: ['empty'],
      visual: null,
    },
    {
      text: 'So look at what the numbers actually do.',
      sourceKind: 'heading',
      blockIndex: 3,
      voice: 'af_heart',
      speed: 1.08,
      pitchCents: 70,
      gain: 1.05,
      pauseAfterMs: 260,
      emphasis: ['numbers'],
      visual: null,
    },
    {
      text: 'This table lines up four temperatures against three things you care about.',
      sourceKind: 'table',
      blockIndex: 4,
      voice: 'af_aoede',
      speed: 1.0,
      pitchCents: 0,
      gain: 1.0,
      pauseAfterMs: 300,
      emphasis: ['four', 'three'],
      visual: { type: 'table', blockIndex: 4 },
    },
    {
      text: 'At room temperature, everything is fine. Full capacity, full charge rate.',
      sourceKind: 'table',
      blockIndex: 4,
      voice: 'af_aoede',
      speed: 1.06,
      pitchCents: 20,
      gain: 1.0,
      pauseAfterMs: 240,
      emphasis: ['fine'],
      visual: { type: 'table', blockIndex: 4, highlight: { row: 0 } },
    },
    {
      text: 'Drop it to freezing and a fifth of your battery quietly stops existing.',
      sourceKind: 'table',
      blockIndex: 4,
      voice: 'af_aoede',
      speed: 0.96,
      pitchCents: -50,
      gain: 1.08,
      pauseAfterMs: 320,
      emphasis: ['fifth'],
      visual: { type: 'table', blockIndex: 4, highlight: { row: 1 } },
    },
    {
      text: 'By minus twenty you are down to forty-five percent, and charging is blocked outright.',
      sourceKind: 'table',
      blockIndex: 4,
      voice: 'af_aoede',
      speed: 0.9,
      pitchCents: -120,
      gain: 1.15,
      pauseAfterMs: 460,
      emphasis: ['blocked'],
      visual: { type: 'table', blockIndex: 4, highlight: { row: 3 } },
    },
    {
      text: 'But the column that actually matters is the last one.',
      sourceKind: 'table',
      blockIndex: 5,
      voice: 'af_kore',
      speed: 0.94,
      pitchCents: -80,
      gain: 1.18,
      pauseAfterMs: 420,
      emphasis: ['last'],
      visual: { type: 'table', blockIndex: 4, highlight: { col: 3 } },
    },
    {
      text: 'Discharging a cold battery is inconvenient. Charging one is destructive.',
      sourceKind: 'prose',
      blockIndex: 5,
      voice: 'af_heart',
      speed: 1.0,
      pitchCents: 40,
      gain: 1.1,
      pauseAfterMs: 300,
      emphasis: ['destructive'],
      visual: {
        type: 'compare',
        title: 'cold battery, two very different mistakes',
        left: {
          label: 'Discharging',
          items: ['Capacity looks lower', 'Comes back when warm', 'No lasting harm'],
        },
        right: {
          label: 'Charging',
          items: ['Lithium plates as metal', 'Capacity gone for good', 'Worst below freezing'],
        },
      },
    },
    {
      text: 'Below freezing, lithium plates onto the anode as metal instead of soaking into it.',
      sourceKind: 'prose',
      blockIndex: 5,
      voice: 'af_heart',
      speed: 1.02,
      pitchCents: 0,
      gain: 1.0,
      pauseAfterMs: 260,
      emphasis: ['metal'],
      visual: null,
    },
    {
      text: 'And that metal never comes back.',
      sourceKind: 'prose',
      blockIndex: 5,
      voice: 'am_fenrir',
      speed: 0.82,
      pitchCents: -200,
      gain: 1.2,
      pauseAfterMs: 780,
      emphasis: ['never'],
      visual: { type: 'quote', text: 'That metal never comes back.' },
    },
    {
      text: "The fix isn't a better battery. It's a thermometer and some patience.",
      sourceKind: 'prose',
      blockIndex: 7,
      voice: 'bf_emma',
      speed: 0.94,
      pitchCents: -40,
      gain: 1.1,
      pauseAfterMs: 520,
      emphasis: ['thermometer', 'patience'],
      visual: {
        type: 'quote',
        text: "The fix isn't a better battery. It's a thermometer and some patience.",
      },
    },
    {
      text: 'Which is exactly what decent firmware does. It refuses.',
      sourceKind: 'code',
      blockIndex: 8,
      voice: 'af_heart',
      speed: 1.1,
      pitchCents: 60,
      gain: 1.05,
      pauseAfterMs: 220,
      emphasis: ['refuses'],
      visual: { type: 'code', blockIndex: 9 },
    },
    {
      text: 'Below zero, the allowed current is zero. No negotiation, no fast charge.',
      sourceKind: 'code',
      blockIndex: 9,
      voice: 'af_heart',
      speed: 1.0,
      pitchCents: -30,
      gain: 1.08,
      pauseAfterMs: 280,
      emphasis: ['zero'],
      visual: { type: 'code', blockIndex: 9, highlight: [2, 3] },
    },
    {
      text: 'Between zero and ten degrees it trickles, at a tenth of what the pack could take.',
      sourceKind: 'code',
      blockIndex: 9,
      voice: 'af_heart',
      speed: 1.06,
      pitchCents: 20,
      gain: 1.0,
      pauseAfterMs: 340,
      emphasis: ['trickles'],
      visual: { type: 'code', blockIndex: 9, highlight: [4, 5] },
    },
    {
      text: "And that trickle isn't a compromise. It's the warm-up.",
      sourceKind: 'prose',
      blockIndex: 10,
      voice: 'af_bella',
      speed: 0.95,
      pitchCents: 70,
      gain: 1.12,
      pauseAfterMs: 300,
      emphasis: ['warm-up'],
      visual: null,
    },
    {
      text: "The cell's own resistance turns that small current straight into heat.",
      sourceKind: 'prose',
      blockIndex: 10,
      voice: 'af_heart',
      speed: 1.08,
      pitchCents: 30,
      gain: 1.0,
      pauseAfterMs: 200,
      emphasis: ['heat'],
      visual: null,
    },
    {
      text: 'Twenty minutes later, the pack is warm enough to take a real charge.',
      sourceKind: 'prose',
      blockIndex: 10,
      voice: 'af_heart',
      speed: 1.0,
      pitchCents: 50,
      gain: 1.1,
      pauseAfterMs: 480,
      emphasis: ['Twenty'],
      visual: {
        type: 'stat',
        value: '20 min',
        label: 'of trickle, and the battery warms itself into working again',
      },
    },
    {
      text: 'So, practically. Keep the thing against your body, not in an outer pocket.',
      sourceKind: 'list',
      blockIndex: 12,
      voice: 'af_sky',
      speed: 1.18,
      pitchCents: 90,
      gain: 1.05,
      pauseAfterMs: 160,
      emphasis: ['body'],
      visual: {
        type: 'bullets',
        title: 'what to actually do',
        items: ['Inner pocket, not outer', 'Warm it before plugging in', 'Trust the jump'],
      },
    },
    {
      text: 'Let a cold phone reach room temperature before you plug it in.',
      sourceKind: 'list',
      blockIndex: 12,
      voice: 'af_sky',
      speed: 1.16,
      pitchCents: 70,
      gain: 1.05,
      pauseAfterMs: 320,
      emphasis: ['before'],
      visual: null,
    },
    {
      text: 'And when the percentage jumps back up, that reading was never a lie.',
      sourceKind: 'list',
      blockIndex: 12,
      voice: 'af_heart',
      speed: 0.96,
      pitchCents: -60,
      gain: 1.1,
      pauseAfterMs: 340,
      emphasis: ['never'],
      visual: {
        type: 'quote',
        text: 'It was never a lie. It was a measurement of what you could reach.',
      },
    },
    {
      text: 'It was just telling you what you could reach at the time.',
      sourceKind: 'list',
      blockIndex: 12,
      voice: 'am_onyx',
      speed: 0.88,
      pitchCents: -180,
      gain: 1.15,
      pauseAfterMs: 900,
      emphasis: ['reach'],
      visual: null,
    },
  ],
}
